# this file is used by .github/workflows/component-codeowners.yml
#
# NOTE component owners must be members of the GitHub OpenTelemetry organization
# so that they can be added to @open-telemetry/java-contrib-triagers
# which in turn is required for them to be auto-assigned as reviewers by the automation
#
# NOTE when updating this file, don't forget to update the README.md files in the associated
# components also
#
# NOTE when adding/updating one of the component names, don't forget to update the associated
# `comp:*` labels
components:
  aws-resources:
    - willarmiros
  aws-xray:
    - willarmiros
  aws-xray-propagator:
    - willarmiros
  consistent-sampling:
    - oertl
    - PeterF778
  samplers:
    - iNikem
    - trask
  jfr-connection:
    - trask
    - jeanbisutti
    - dsgrieve
  jfr-events:
    - sfriberg
  jfr-streaming:
    - breedx-splk
    - jack-berg
    - kittylyst
  jmx-metrics:
    - dehaansa
    - Mrod1598
    - rmfitzpatrick
    - breedx-splk
  maven-extension:
    - cyrille-leclerc
    - kenfinnigan
  micrometer-meter-provider:
    - HaloFour
  noop-api:
    - jack-berg
  prometheus-collector:
    - jkwatson
  resource-providers:
    - breedx-splk
    - mateuszrzeszutek
    - laurit
  runtime-attach:
    - iNikem
    - jeanbisutti
  static-instrumenter:
    - anosek-an
