timeout = 30
retry_wait_time = 5
max_retries = 6
max_concurrency = 1

# Stealth
user_agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:128.0) Gecko/20100101 Firefox/128.0"

# Check fragments in links
include_fragments = true

# excluding links to pull requests and issues is done for performance
# sonatype snapshots are currrently unbrowseable
exclude = [
  "^https://github.com/open-telemetry/opentelemetry-java-contrib/(issues|pull)/\\d+$",
  '^https://central.sonatype.com/service/rest/repository/browse/maven-snapshots/io/opentelemetry/contrib/$',
]


