/*
 * Copyright The OpenTelemetry Authors
 * SPDX-License-Identifier: Apache-2.0
 */

package io.opentelemetry.opamp.client.internal;

import com.github.f4b6a3.uuid.UuidCreator;
import com.google.errorprone.annotations.CanIgnoreReturnValue;
import io.opentelemetry.opamp.client.internal.impl.OpampClientImpl;
import io.opentelemetry.opamp.client.internal.impl.OpampClientState;
import io.opentelemetry.opamp.client.internal.request.service.HttpRequestService;
import io.opentelemetry.opamp.client.internal.request.service.RequestService;
import io.opentelemetry.opamp.client.internal.request.service.WebSocketRequestService;
import io.opentelemetry.opamp.client.internal.state.State;
import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import javax.annotation.Nullable;
import opamp.proto.AgentCapabilities;
import opamp.proto.AgentDescription;
import opamp.proto.AnyValue;
import opamp.proto.ArrayValue;
import opamp.proto.KeyValue;
import opamp.proto.RemoteConfigStatus;

/**
 * This class is internal and is hence not for public use. Its APIs are unstable and can change at
 * any time.
 *
 * <p>Builds an {@link OpampClient} instance.
 */
public final class OpampClientBuilder {
  private final Map<String, AnyValue> identifyingAttributes = new HashMap<>();
  private final Map<String, AnyValue> nonIdentifyingAttributes = new HashMap<>();
  private long capabilities = 0;
  @Nullable private byte[] instanceUid;
  @Nullable private State.EffectiveConfig effectiveConfigState;
  @Nullable private RequestService service;

  OpampClientBuilder() {}

  /**
   * Sets an implementation of a {@link RequestService} to handle the request's sending process.
   * There are 2 possible options, either {@link HttpRequestService} to use HTTP, or {@link
   * WebSocketRequestService} to use WebSocket.
   *
   * @param service The request service implementation.
   * @return this
   */
  @CanIgnoreReturnValue
  public OpampClientBuilder setRequestService(RequestService service) {
    this.service = service;
    return this;
  }

  /**
   * Sets the Agent's <a
   * href="https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#agenttoserverinstance_uid">instance_uid</a>
   * value. A random one is generated by default.
   *
   * @param value The AgentToServer.instance_uid value.
   * @return this
   */
  @CanIgnoreReturnValue
  public OpampClientBuilder setInstanceUid(byte[] value) {
    this.instanceUid = value;
    return this;
  }

  /**
   * Puts a string attribute into the <a
   * href="https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#agentdescriptionidentifying_attributes">identifying_attributes</a>
   * field.
   *
   * @param key The attribute key.
   * @param value The attribute value.
   * @return this
   */
  @CanIgnoreReturnValue
  public OpampClientBuilder putIdentifyingAttribute(String key, String value) {
    identifyingAttributes.put(key, createStringValue(value));
    return this;
  }

  /**
   * Puts a boolean attribute into the <a
   * href="https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#agentdescriptionidentifying_attributes">identifying_attributes</a>
   * field.
   *
   * @param key The attribute key.
   * @param value The attribute value.
   * @return this
   */
  @CanIgnoreReturnValue
  public OpampClientBuilder putIdentifyingAttribute(String key, boolean value) {
    identifyingAttributes.put(key, createBooleanValue(value));
    return this;
  }

  /**
   * Puts a long (proto int64) attribute into the <a
   * href="https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#agentdescriptionidentifying_attributes">identifying_attributes</a>
   * field.
   *
   * @param key The attribute key.
   * @param value The attribute value.
   * @return this
   */
  @CanIgnoreReturnValue
  public OpampClientBuilder putIdentifyingAttribute(String key, long value) {
    identifyingAttributes.put(key, createLongValue(value));
    return this;
  }

  /**
   * Puts a double attribute into the <a
   * href="https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#agentdescriptionidentifying_attributes">identifying_attributes</a>
   * field.
   *
   * @param key The attribute key.
   * @param value The attribute value.
   * @return this
   */
  @CanIgnoreReturnValue
  public OpampClientBuilder putIdentifyingAttribute(String key, double value) {
    identifyingAttributes.put(key, createDoubleValue(value));
    return this;
  }

  /**
   * Puts a string array attribute into the <a
   * href="https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#agentdescriptionidentifying_attributes">identifying_attributes</a>
   * field.
   *
   * @param key The attribute key.
   * @param values The attribute values.
   * @return this
   */
  @CanIgnoreReturnValue
  public OpampClientBuilder putIdentifyingAttribute(String key, String... values) {
    if (values == null) {
      return this;
    }
    identifyingAttributes.put(key, createArrayValue(createStringValueList(values)));
    return this;
  }

  /**
   * Puts a boolean array attribute into the <a
   * href="https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#agentdescriptionidentifying_attributes">identifying_attributes</a>
   * field.
   *
   * @param key The attribute key.
   * @param values The attribute values.
   * @return this
   */
  @CanIgnoreReturnValue
  public OpampClientBuilder putIdentifyingAttribute(String key, boolean... values) {
    if (values == null) {
      return this;
    }
    identifyingAttributes.put(key, createArrayValue(createBooleanValueList(values)));
    return this;
  }

  /**
   * Puts a long (proto int64) array attribute into the <a
   * href="https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#agentdescriptionidentifying_attributes">identifying_attributes</a>
   * field.
   *
   * @param key The attribute key.
   * @param values The attribute values.
   * @return this
   */
  @CanIgnoreReturnValue
  public OpampClientBuilder putIdentifyingAttribute(String key, long... values) {
    if (values == null) {
      return this;
    }
    identifyingAttributes.put(key, createArrayValue(createLongValueList(values)));
    return this;
  }

  /**
   * Puts a double array attribute into the <a
   * href="https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#agentdescriptionidentifying_attributes">identifying_attributes</a>
   * field.
   *
   * @param key The attribute key.
   * @param values The attribute values.
   * @return this
   */
  @CanIgnoreReturnValue
  public OpampClientBuilder putIdentifyingAttribute(String key, double... values) {
    if (values == null) {
      return this;
    }
    identifyingAttributes.put(key, createArrayValue(createDoubleValueList(values)));
    return this;
  }

  /**
   * Puts a string attribute into the <a
   * href="https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#agentdescriptionnon_identifying_attributes">non_identifying_attributes</a>
   * field.
   *
   * @param key The attribute key
   * @param value The attribute value.
   * @return this
   */
  @CanIgnoreReturnValue
  public OpampClientBuilder putNonIdentifyingAttribute(String key, String value) {
    nonIdentifyingAttributes.put(key, createStringValue(value));
    return this;
  }

  /**
   * Puts a boolean attribute into the <a
   * href="https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#agentdescriptionnon_identifying_attributes">non_identifying_attributes</a>
   * field.
   *
   * @param key The attribute key
   * @param value The attribute value.
   * @return this
   */
  @CanIgnoreReturnValue
  public OpampClientBuilder putNonIdentifyingAttribute(String key, boolean value) {
    nonIdentifyingAttributes.put(key, createBooleanValue(value));
    return this;
  }

  /**
   * Puts a long (proto int64) attribute into the <a
   * href="https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#agentdescriptionnon_identifying_attributes">non_identifying_attributes</a>
   * field.
   *
   * @param key The attribute key
   * @param value The attribute value.
   * @return this
   */
  @CanIgnoreReturnValue
  public OpampClientBuilder putNonIdentifyingAttribute(String key, long value) {
    nonIdentifyingAttributes.put(key, createLongValue(value));
    return this;
  }

  /**
   * Puts a double attribute into the <a
   * href="https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#agentdescriptionnon_identifying_attributes">non_identifying_attributes</a>
   * field.
   *
   * @param key The attribute key
   * @param value The attribute value.
   * @return this
   */
  @CanIgnoreReturnValue
  public OpampClientBuilder putNonIdentifyingAttribute(String key, double value) {
    nonIdentifyingAttributes.put(key, createDoubleValue(value));
    return this;
  }

  /**
   * Puts a string array attribute into the <a
   * href="https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#agentdescriptionnon_identifying_attributes">non_identifying_attributes</a>
   * field.
   *
   * @param key The attribute key
   * @param values The attribute values.
   * @return this
   */
  @CanIgnoreReturnValue
  public OpampClientBuilder putNonIdentifyingAttribute(String key, String... values) {
    if (values == null) {
      return this;
    }
    nonIdentifyingAttributes.put(key, createArrayValue(createStringValueList(values)));
    return this;
  }

  /**
   * Puts a boolean array attribute into the <a
   * href="https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#agentdescriptionnon_identifying_attributes">non_identifying_attributes</a>
   * field.
   *
   * @param key The attribute key
   * @param values The attribute values.
   * @return this
   */
  @CanIgnoreReturnValue
  public OpampClientBuilder putNonIdentifyingAttribute(String key, boolean... values) {
    if (values == null) {
      return this;
    }
    nonIdentifyingAttributes.put(key, createArrayValue(createBooleanValueList(values)));
    return this;
  }

  /**
   * Puts a long (proto int64) array attribute into the <a
   * href="https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#agentdescriptionnon_identifying_attributes">non_identifying_attributes</a>
   * field.
   *
   * @param key The attribute key
   * @param values The attribute values.
   * @return this
   */
  @CanIgnoreReturnValue
  public OpampClientBuilder putNonIdentifyingAttribute(String key, long... values) {
    if (values == null) {
      return this;
    }
    nonIdentifyingAttributes.put(key, createArrayValue(createLongValueList(values)));
    return this;
  }

  /**
   * Puts a double array attribute into the <a
   * href="https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#agentdescriptionnon_identifying_attributes">non_identifying_attributes</a>
   * field.
   *
   * @param key The attribute key
   * @param values The attribute values.
   * @return this
   */
  @CanIgnoreReturnValue
  public OpampClientBuilder putNonIdentifyingAttribute(String key, double... values) {
    if (values == null) {
      return this;
    }
    nonIdentifyingAttributes.put(key, createArrayValue(createDoubleValueList(values)));
    return this;
  }

  /**
   * Adds the AcceptsRemoteConfig and ReportsRemoteConfig capabilities to the Client so that the
   * Server can offer remote config values as explained <a
   * href="https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#agentdescriptionidentifying_attributes">here</a>.
   *
   * @return this
   */
  @CanIgnoreReturnValue
  public OpampClientBuilder enableRemoteConfig() {
    capabilities =
        capabilities
            | AgentCapabilities.AgentCapabilities_AcceptsRemoteConfig.getValue()
            | AgentCapabilities.AgentCapabilities_ReportsRemoteConfig.getValue();
    return this;
  }

  /**
   * Adds the ReportsEffectiveConfig capability to the Client so that the Server expects the
   * Client's effective config report, as explained <a
   * href="https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#agentdescriptionidentifying_attributes">here</a>.
   *
   * @return this
   */
  @CanIgnoreReturnValue
  public OpampClientBuilder enableEffectiveConfigReporting() {
    capabilities =
        capabilities | AgentCapabilities.AgentCapabilities_ReportsEffectiveConfig.getValue();
    return this;
  }

  /**
   * Sets the effective config state implementation. It should call {@link
   * State.EffectiveConfig#notifyUpdate()} whenever it has changes that have not been sent to the
   * server.
   *
   * @param effectiveConfigState The state implementation.
   * @return this
   */
  @CanIgnoreReturnValue
  public OpampClientBuilder setEffectiveConfigState(State.EffectiveConfig effectiveConfigState) {
    this.effectiveConfigState = effectiveConfigState;
    return this;
  }

  public OpampClient build() {
    if (service == null) {
      throw new IllegalStateException(
          "The request service is not set. You must provide it by calling setRequestService()");
    }
    List<KeyValue> protoIdentifyingAttributes = new ArrayList<>();
    List<KeyValue> protoNonIdentifyingAttributes = new ArrayList<>();
    identifyingAttributes.forEach(
        (key, value) -> protoIdentifyingAttributes.add(createKeyValue(key, value)));
    nonIdentifyingAttributes.forEach(
        (key, value) -> protoNonIdentifyingAttributes.add(createKeyValue(key, value)));
    if (instanceUid == null) {
      instanceUid = createRandomInstanceUid();
    }
    if (effectiveConfigState == null) {
      effectiveConfigState = createEffectiveConfigNoop();
    }
    OpampClientState state =
        new OpampClientState(
            new State.RemoteConfigStatus(new RemoteConfigStatus.Builder().build()),
            new State.SequenceNum(1L),
            new State.AgentDescription(
                new AgentDescription.Builder()
                    .identifying_attributes(protoIdentifyingAttributes)
                    .non_identifying_attributes(protoNonIdentifyingAttributes)
                    .build()),
            new State.Capabilities(capabilities),
            new State.InstanceUid(instanceUid),
            new State.Flags(0L),
            effectiveConfigState);
    return OpampClientImpl.create(service, state);
  }

  private static State.EffectiveConfig createEffectiveConfigNoop() {
    return new State.EffectiveConfig() {
      @Nullable
      @Override
      public opamp.proto.EffectiveConfig get() {
        return null;
      }
    };
  }

  private static AnyValue createStringValue(String value) {
    return new AnyValue.Builder().string_value(value).build();
  }

  private static AnyValue createBooleanValue(boolean value) {
    return new AnyValue.Builder().bool_value(value).build();
  }

  private static AnyValue createLongValue(long value) {
    return new AnyValue.Builder().int_value(value).build();
  }

  private static AnyValue createDoubleValue(double value) {
    return new AnyValue.Builder().double_value(value).build();
  }

  private static List<AnyValue> createStringValueList(String[] values) {
    List<AnyValue> anyValues = new ArrayList<>();
    for (String value : values) {
      anyValues.add(createStringValue(value));
    }
    return anyValues;
  }

  private static List<AnyValue> createBooleanValueList(boolean[] values) {
    List<AnyValue> anyValues = new ArrayList<>();
    for (boolean value : values) {
      anyValues.add(createBooleanValue(value));
    }
    return anyValues;
  }

  private static List<AnyValue> createLongValueList(long[] values) {
    List<AnyValue> anyValues = new ArrayList<>();
    for (long value : values) {
      anyValues.add(createLongValue(value));
    }
    return anyValues;
  }

  private static List<AnyValue> createDoubleValueList(double[] values) {
    List<AnyValue> anyValues = new ArrayList<>();
    for (double value : values) {
      anyValues.add(createDoubleValue(value));
    }
    return anyValues;
  }

  private static AnyValue createArrayValue(List<AnyValue> values) {
    return new AnyValue.Builder()
        .array_value(new ArrayValue.Builder().values(values).build())
        .build();
  }

  private static KeyValue createKeyValue(String key, AnyValue value) {
    return new KeyValue.Builder().key(key).value(value).build();
  }

  public static byte[] createRandomInstanceUid() {
    UUID uuid = UuidCreator.getTimeOrderedEpoch();
    ByteBuffer buffer = ByteBuffer.allocate(16);
    buffer.putLong(uuid.getMostSignificantBits());
    buffer.putLong(uuid.getLeastSignificantBits());
    return buffer.array();
  }
}
