name: Assign Copilot as reviewer

on:
  pull_request_target:
    types:
      - ready_for_review

permissions:
  contents: read

jobs:
  assign-copilot:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Copilot as reviewer
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.COPILOT_ASSIGNING_PAT }}
          script: |
            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              reviewers: ['copilot-swe-agent']
            });
