name: Build Pull Request

on:
  pull_request:
  merge_group:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  common:
    uses: ./.github/workflows/build-common.yml
    with:
      cache-read-only: true
      # retry in merge queue to avoid unnecessary failures
      max-test-retries: ${{ github.event_name == 'merge_group' && 5 || 0 }}

  lint:
    uses: ./.github/workflows/reusable-lint.yml

  required-status-check:
    if: always()
    needs:
      - common
      - lint # wait for lint to complete, but don't require it to pass for merging
    runs-on: ubuntu-latest
    steps:
      # The reusable workflow success depends on all its jobs passing
      - if: needs.common.result != 'success'
        run: exit 1 # fail
