# This action assigns and requires approval from owners of components for
# PRs that are open against those components. Components are defined in
# .github/component_owners.yaml as individual paths within this repository.
name: Component Owners

on:
  pull_request_target:

jobs:
  run_self:
    runs-on: ubuntu-latest
    name: Auto Assign Owners
    steps:
      - uses: dyladan/component-owners@main
