name: Zizmor GitHub Actions Security Analysis

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  zizmor:
    name: Zizmor Security Analysis
    permissions:
      contents: read
      security-events: write
    uses: open-telemetry/shared-workflows/.github/workflows/zizmor.yml@7c49790392da7de86fdb4bb968446f9cb8461eb8 # v0.3.1
